### ISSUE TITLE
'epochnum' endpoint returns an empty result when in epoch 0

### ISSUE THREAD

**Issue by AmitShaul** [spacemeshos/api#137] opened 2021-03-08 14:52 UTC
'epochnum' endpoint returns an empty result when in epoch 0

result = {'epochnum': {}}
wanted result = {'epochnum': {'value': 0}}

**Comment by avive** [comment] 2021-03-08 16:49
This also affects explore and dash on net id 126. This is a new issue due to recent api changes. See https://explorer-126.spacemesh.io/epochs - missing epoch 0. @lrettig

**Comment by lrettig** [comment] 2021-03-16 15:01
This is a duplicate of #87. It's an artifact of the grpc design and we cannot change it. Default values are always empty, and zero is the default value for an integer.

**Closed by lrettig** 2021-03-16 15:01 UTC
Labels: bug, invalid

**Comment by avive** [comment] 2021-03-16 15:13
Shouldn't GRPC clients just handle this gracefully?

**Comment by lrettig** [comment] 2021-03-19 23:20
> Shouldn't GRPC clients just handle this gracefully?

Yes. The only alternative here is to change the type of epochnum, layernum, etc. so it's not an int, and I don't think we want to do that.
