### ISSUE TITLE
Block data

### ISSUE THREAD

**Issue by avive** [spacemeshos/api#124] opened 2020-11-30 10:21 UTC
I think we are missing these fields from the Block data item returned by the API and that each block has this data. It is required for explorer.

- ATX ID - the id of the ATX that made the smesher who submitted the block eligible to submit it. I think it is referenced from every block.
- Smesher ID - the id of the smesher who submitted that block. It can be obtained from the ATX identified by ATX ID as well.

@lrettig @noamnelke - am I missing something here?

**Comment by lrettig** [comment] 2020-11-30 17:01
Duplicate of #113, let's discuss there

**Closed by lrettig** 2020-11-30 17:01 UTC
